### ISSUE TITLE
Doesn't work good with firefox

### ISSUE THREAD

**Issue by Dudo1985** [fredolss/rater-js#1]
Hello,
Seems like I've some problem with Firefox, see gif attacched 
![rater-js-ff](https://user-images.githubusercontent.com/5710734/39865173-524a439a-544c-11e8-936c-9edba916302d.gif)

Works fine with Chrome, Edge, IE and Opera

**Comment by fredolss** [comment]
Hi Dario,

Thanks for testing. I will look into this.
