### ISSUE TITLE
Decimal rating vertically instead of horizontally

### ISSUE THREAD

**Issue by spacecat** [fredolss/rater-js#10]
Last question I believe :)

Is it possible to make the rendering of the decimal rating vertically instead of the regular horizontally?

I'm asking because the icon I'm using is a menstrual cup and it would be cool if you could actually think of the decimals as a way of "filling the cup" if you know what I mean.

If you're busy, you could point me to the right section in the code, give me some pointers and I can try to create a pull request.

**Comment by spacecat** [comment]
@fredolss please try to implement this 😄

**Comment by fredolss** [comment]
There is a branch called vertical-rating.  See example in the bottom of the example page.

**Comment by spacecat** [comment]
Sorry, my bad, was not clear enough,
please see image below - that's the actual feature request I had in mind.
![Image](https://imgur.com/wDcC6J4.png)

I'm sure there are others who will find the current implementation valuable but still can't help but to feel a bit embarressed 🙈 Still very thankful for the effort.

**Comment by fredolss** [comment]
This would require a completely different logic and is too much work I think. This widget is a simple repeating background image and we just set the width of the element. Is it always 5 cups?  Is it enough to support half stars? There are many other rating widgets you can try that maybe work better for your use case.
