### ISSUE TITLE
Reset rater-js

### ISSUE THREAD

**Issue by spacecat** [fredolss/rater-js#11]
How do I reset the rater after a user has rated something once?

Do I call `dispose()` and then reinitialize the rater object? Or can I disable and then enable it using `disable()` and `enable()`? Or do I just set the rating back to 0 with `setRating()`?

**Comment by fredolss** [comment]
there is not method for this right now. I plan to add a clear or reset method. You can use setRating and pass in undefined

**Comment by fredolss** [comment]
Added clear method so this is supported now.
