### ISSUE TITLE
RTL support?

### ISSUE THREAD

**Issue by Dudo1985** [fredolss/rater-js#12]
Hi, is it possible to add support for rtl languages?

Best, 
Dario

**Comment by Dudo1985** [comment]
I've forked and just added RTL and AR to the example, is now live here

https://dudo1985.github.io/rater-js/example/

I've added a litle of css to let it work better for rtl (it works good when readonly is true), but, as you can see, seems like on mouseover the target change and it break everything.

**Comment by Dudo1985** [comment]
I've done it :)

Take a look here https://dudo1985.github.io/rater-js/example/

I will create a pull requesto soon

**Comment by fredolss** [comment]
Looks good :)

**Comment by samirKamalGhoneim** [comment]
not working probably :(

**Comment by samirKamalGhoneim** [comment]
please add to documentation that you must add `reverse:true` while construct `rate` object
