### ISSUE TITLE
Add property of the rater object to return the original element

### ISSUE THREAD

**Issue by johnnyshields** [fredolss/rater-js#16]
Currently it seems there is no way to get the original HTML element used for the rater from the `this` object in the `rateCallback()` function

**Comment by fredolss** [comment]
Thanks for noticing this. I'm not sure about the best practice when creating these type of components. I'm not sure if **this** should point to the element or the component instance. We could have a get property on the component for this or just make this be the element. If **this** is the element then we need to find some other way to get the instance like passing it to the callback. Maybe you have some resources to point to so we can follow best practices?

**Comment by fredolss** [comment]
I added an element getter on the rater object.

**Comment by johnnyshields** [comment]
@fredolss awesome, thanks! This is very useful for me.

Re: `this`, for JQuery components I would think the principle of least surprise in callbacks is to have `this` be the original element and have the `rater` object be an argument to the callback. That would feel the most "JQuery-like" to me. But doing that change would likely break things for many users so I think fine as-is.
