### ISSUE TITLE
ES support

### ISSUE THREAD

**Issue by arlopezg** [fredolss/rater-js#18]
Hello,

Is it possible to include ES Modules support? 

That way, we could just `import { foo } from 'rater-js'` the widget in our apps :)

Cheers

**Comment by fredolss** [comment]
Hi,

This is already supported it seems. I tried it out.

### Html

<script type="module" src="main.js"></script>

### main.js

`import * as RaterJs from './raterJs.js';`

Now you can use it like this:


```
	let rater = RaterJs ( {
		element:document.querySelector("#rater"), 
		rateCallback:function rateCallback(rating, done) {
			this.setRating(rating); 
			done(); 
		}
	}); 

```

raterJs.js is the built js file. Just move this file where you need it. Does this work for you?
