### ISSUE TITLE
Allow a decimal rating

### ISSUE THREAD

**Issue by Dudo1985** [fredolss/rater-js#2]
Hello, 
is it possible to rate an item with decimal precision?

A new configuration proprerty, something like "step" or similiar will be awesome, e.g.

step: 0.1 // 0.1 deciamal precision
step: 0.5 // half int precision

Apologize for my English :)

**Comment by fredolss** [comment]
Hi,

Thanks for your input. 

We currently don't support this, but since you have an interest in this I think it will not be so hard to implement. I will take a look at this.

**Comment by fredolss** [comment]
This is fixed in latest version
