### ISSUE TITLE
Add possibility to change icons color

### ISSUE THREAD

**Issue by archi-tektur** [fredolss/rater-js#22]
I know that surely you have more important stuff to do, but possibility to change icon's color would be a really nice function.

**Comment by fredolss** [comment]
The svg is a background image. Changing the colors is not possible I think without changing the image.

You can take the default image and change the color manually and then use the new image as backround image instead. Will this work for you?

**Comment by archi-tektur** [comment]
Sure, but I need a possibility to specify own image in config then. Another solution is filling your SVG with CSS like here: https://css-tricks.com/almanac/properties/f/fill/

**Comment by fredolss** [comment]
That only works if its an svg element. It's a background. You can override with css. See the readme.

**Comment by oTiMo** [comment]
@fredolss : it could be usefull to use to use css propery `mask-image` (https://codepen.io/noahblon/post/coloring-svgs-in-css-background-images)

could you re open this issue ?
