### ISSUE TITLE
Imporvement recommendation

### ISSUE THREAD

**Issue by yodeco** [fredolss/rater-js#4]
Hello, I was really thrilled with your plugin, and want thank you for your work. On my side, I would like to ask you add a new feature, let's name that prop  "resetOnHover". Some details:
- When user hover stars, we highlight selected stars;
- When user clicks, we apply setRating() method;
- When user hovers again on same stars, we START highlighting selected stars
- If user did NO click and did blur from stars, we show PREVIOUS rating;
- If user hovers and clicks, we apply setRating() method

I managed to do it dummy way by 
1. function onStarClick(e)
I commented

// if (isRating === true) {
    //   return;
    // }

then
2. function onMouseMove(e)
  // if (disabled === true || isRating === true) {
    //   return;
    // }

And it worked as I wanted, but I suppose that feature will be required. Thanks.

**Comment by fredolss** [comment]
Hi,

Thanks for the input. I'm not sure I understand. How is this different from how it works today? 

When isRating is true there is a rating in progress and done hasn't been called so this logic is required.

**Comment by yodeco** [comment]
Hello, I do apologize, problem was on my side, widget has that logic, so what you stated above is true. Thanks, I close issue.
