### ISSUE TITLE
Has rater-js been optimized/tested for touch/smart devices?

### ISSUE THREAD

**Issue by spacecat** [fredolss/rater-js#8]
Has rater-js been optimized/tested for touch/smart devices?

**Comment by fredolss** [comment]
Hi,

If you mean if supports touch events, then no.

**Comment by luiscastro193** [comment]
> +1, for some reason I have to double-tap on iOS Safari for the callback to fire :(
> 
> Reason: https://css-tricks.com/annoying-mobile-double-tap-link-issue/

Actually, I like it since you can use ratingText to warn the user.

**Comment by spacecat** [comment]
> > +1, for some reason I have to double-tap on iOS Safari for the callback to fire :(
> > Reason: https://css-tricks.com/annoying-mobile-double-tap-link-issue/
> 
> Actually, I like it since you can use ratingText to warn the user.

Can you explain the double-tap issue on iOS Safari, @luiscastro193 ? 
I hope this is not a show stopper for me because a lot of people use iOS Safari.

**Comment by luiscastro193** [comment]
Fist tap fills the stars and triggers ratingText but the callback isn't fired until the second callback. So users will think the rating is already done when actually it isn't, unless you warn them with ratingText.

**Comment by fredolss** [comment]
I will update to use title attribute instead. This will solve these problems I think.

**Comment by jreviews** [comment]
@fredolss Thanks for putting together this script. Have you been able to make changes for mobile use? When I try it on your demo and my test site I get the following error in the browser console.

`Uncaught TypeError: this.setRating is not a function`

**Comment by Dudo1985** [comment]
Same problem here, on mobile seems doesn't work anymore

**Comment by jreviews** [comment]
Commenting the following lines fixes the issue for me:

```
	elem.addEventListener("touchmove", handleMove, false);
	elem.addEventListener("touchstart", handleStart, false);
	elem.addEventListener("touchend", handleEnd, false);
	elem.addEventListener("touchcancel", handleCancel, false);
```
So obviously the touch events are breaking it.

**Comment by fredolss** [comment]
Sorry for the delay. Now it's fixed.
