### ISSUE TITLE
Average rating

### ISSUE THREAD

**Issue by spacecat** [fredolss/rater-js#9]
Hi @fredolss 

Got another question - Just wondering about the average rating. Saw that other issue btw talking about this.

What I'm wondering is:

Does the widget have support for decimal rating in the actual rendering of the SVG icon?

Here is an example of what I'm talking about:

[https://imgur.com/kUd2Wsy](https://imgur.com/kUd2Wsy)

**Comment by fredolss** [comment]
Hi,

Yes, it does. Set the step property
